version: '3.7'

services:
 
  kibana: 
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - 8080:80
    environment: 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
    - ./docker/kibana/config.yml:/usr/share/kibana/config/kibana.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 9200:9200
    environment: 
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
   volumes:
    - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local


