version: '3.7'

services:
 
  kibana: 
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - target: 5601
        published: 5601
    environment: 
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
    - target: 9200
      published: 9200
    environment: 
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
    - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local


